### ISSUE TITLE
Incompatibility with python 3.9.1 version?

### ISSUE THREAD

**Issue by tospines** [cosmicrays/hermes#13]
I am trying to install Hermes in a new environment, where I am using the Python version 3.9.1, and I get the following error when running the CMAKE_PREFIX_PATH=$HERMES_DIR cmake -DCMAKE_INSTALL_PREFIX=$HERMES_DIR -DENABLE_TESTING=On .. command, in the build directory:

CMake Error at /software/sse/manual/CMake/3.12.1/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "3.9.1", but required
  is at least "39" (found /home/x_pedde/.virtualenvs/hermes/bin/python) 

Any idea on what is the problem here?

**Comment by adundovi** [comment]
Thanks for reporting an issue. I can reproduce this as well. The cause seems to come from Pybind11. Use `-DPYBIND11_PYTHON_VERSION=3.9` as an argument for cmake to fix it for the moment, like this:
```
CMAKE_PREFIX_PATH=$HERMES_DIR cmake -DCMAKE_INSTALL_PREFIX=$HERMES_DIR -DENABLE_TESTING=On -DCMAKE_BUILD_TYPE=Release -DPYBIND11_PYTHON_VERSION=3.9 ..
```
And I'll take a look how to fix it without the need for a user intervention.
