### ISSUE TITLE
Installation errors in ubuntu 18.04

### ISSUE THREAD

**Issue by tospines** [cosmicrays/hermes#2]
Hi, I am trying to install Hermes in my computer (I use ubuntu 18.04 in a session of MobaXterm) and the compilation shows me several errors such as: 
  /home/Diffuse_models/hermes/include/hermes/integrators/PiZeroIntegrator.h:26:30: error: ‘RingModel’ is not a member of
  ‘hermes::neutralgas’
    std::shared_ptr<neutralgas::RingModel> ngdensity;
  /home/Diffuse_models/hermes/include/hermes/integrators/PiZeroIntegrator.h:26:30: error: ‘RingModel’ is not a member of
  ‘hermes::neutralgas’
  /home/Diffuse_models/hermes/include/hermes/integrators/PiZeroIntegrator.h:26:39: error: template argument 1 is invalid
    std::shared_ptr<neutralgas::RingModel> ngdensity;

And other similar ones regarding the declaration of variables not found. I think this is due to my compiler (I am using gcc 8.4.0.)

In addition, when using the command cmake .. I find that CFitsio and doxygen are not found. I even tried a command like: cmake .. -DCFITSIO=/home/Diffuse_models/cfitsio-3.49/   but it does not find it and I get the following warning: 
  Manually-specified variables were not used by the project:
    CFITSIO

Any ideas on how could I fix these problems?

Thank you in advance.

**Comment by carmeloevoli** [comment]
Is not -DCIFITSIO but -DCFITSIO

**Comment by tospines** [comment]
Sorry for the typo, I used -DCFITSIO=...

**Comment by carmeloevoli** [comment]
looking at the CMake I see two possible solutions:
1) set the environment variable CFITSIO to the location of cfitsio.h
2) add the CFITSIO library path to the LD_LIBRARY_PATH

**Comment by tospines** [comment]
I have tried both, but it gives me the same warning in the cmake and errors when using make -j.
In fact, the message it gives me at the end of the cmake (Manually-specified variables were not used by the project:  CFITSIO) makes me think I am not specifying correctly the folder it needs. However, I have tried several combinations as .../cfitsio-3.49/lib   .../cfitsio-3.49/include  .../cfitsio-3.49/  but I got the same warning and error messages

**Comment by carmeloevoli** [comment]
don't use -DCFITSIO from now on, check first if you set the glob variables properly by doing this:
`echo $CFITSIO`
`echo $LD_LIBRARY_PATH`

**Comment by tospines** [comment]
These are the outputs:
echo $CFITSIO
:/home/tospines/Diffuse_models/cfitsio-3.49/

echo $LD_LIBRARY_PATH
:/home/Diffuse_models/gsl-2.6/lib:/tmp/Qt4.8/qt-everywhere-opensource-src-4.8.6/lib/:/home/Diffuse_models/cfit
sio-3.49/lib:/home/tospines/Diffuse_models/cfitsio-3.49:/home/tospines/Diffuse_models/cfitsio-3.49/include:/home/tospines/Diffuse_models/gsl-2.6/lib:/tmp/Qt4.8/qt-everywhere-opensource-src-4.8.6/lib/:/home/Diffuse_models/cfitsio-3.49/lib:/home/Diffuse_models/cfitsio-3.49:/home/Diffuse_models/cfitsio-3.49/include

**Comment by tospines** [comment]
The issue was solved when installing cfitsio in the /usr/include folder.

Thank you!
