### ISSUE TITLE
New integrator: Gamma-ray absorption on CMB only

### ISSUE THREAD

**Issue by carmeloevoli** [cosmicrays/hermes#20]
In order to speed up the pi0 integrator including gamma-ray absorption we should consider the case in which CMB is the only photon field. Being spatially uniform it simplifies the runtime calculation of the optical depth.

**Comment by adundovi** [comment]
Should we do this as a new integrator, derived from the current pi0?

**Comment by carmeloevoli** [comment]
Yes, something like `PiZeroCmbAbsorptionIntegrator.h`

**Comment by carmeloevoli** [comment]
My notes about the calculation of the absorption coefficient for CMB can be found [here](https://www.dropbox.com/s/prdpqgv5lvr4pu1/PeV_gamma_ray_absorption.pdf?dl=0)

The new integrator is very similar to pi0, just adding a function which computes `K(E)` and using it following my equation (7).

Notice however that my equation for `K(E)` (equation 4) looks different than that implemented now in HERMES.

**Comment by carmeloevoli** [comment]
I am working on a branch to implement CMB absorption.
Notice that I had to modify the `BreitWheeler` class with the new expression. 
Now I don't know how to write this:
https://github.com/cosmicrays/hermes/blob/79c19ef652d609b32139084a4a0a483c5ffb17f6/src/integrators/PiZeroCmbAbsorptionIntegrator.cpp#L9

**Comment by adundovi** [comment]
`std::expm1(static_cast<double>(eps / kT))` if you want to override HERMES units...

**Comment by carmeloevoli** [comment]
It is a ratio of energies, shouldn't be a "QNumber"?

**Comment by adundovi** [comment]
Yes, although `QNumber` is dimensionless, it is still a HERMES unit, and a `std` function such as `expm1` will not accept it without casting it to double.

**Comment by carmeloevoli** [comment]
thanks, in fact I was trying to use this:
https://github.com/cosmicrays/hermes/blob/51d8e4b6ff4943838c17c0005d5a75c5909b9762/include/hermes/units/UnitsFunctions.h#L18
but of course it doesn't work if I use `std`

**Comment by carmeloevoli** [comment]
I am thinking that it is better to have in the public code only a `PiZeroAbsorptionIntegrator` with only CMB as photonfield. We will work separately on to make it general but at the moment is way too slow.

Another point, I don't understand with `PiZeroAbsorptionIntegrator` is not derived from `PiZeroIntegrator` with only 1 or 2 functions overrided. In this way, if we change something on `PiZeroIntegrator` automatically is inherited by `PiZeroAbsorptionIntegrator`.

In the branch, I'm working on this idea.

**Comment by carmeloevoli** [comment]
I wrote the function to compute the absorption coefficient now only dependent on gamma energy. 

Do you see any problem in this function?

https://github.com/cosmicrays/hermes/blob/51d8e4b6ff4943838c17c0005d5a75c5909b9762/src/integrators/PiZeroAbsorptionIntegrator.cpp#L221

**Comment by carmeloevoli** [comment]
The `PiZeroAbsorptionIntegrator` is now working in C++. We should modify `python/integrators.cpp` to have it also in python.

**Comment by carmeloevoli** [comment]
It is as fast as `PiZeroIntegrator`. I had a minimal approach by implementing only the few functions that are different from `PiZeroIntegrator`. I think that we should keep this Integrator in HERMES and leaving the absorption on a generic photon field to future updates.

**Comment by carmeloevoli** [comment]
Branch merged and CI working. That's all folks!
