### ISSUE TITLE
parallelization

### ISSUE THREAD

**Issue by danielegaggero** [cosmicrays/hermes#21]
Hi, very quick dummy questions:

1) how do I disable multi-threading, or set a different number of threads?
I noticed this line *env_num_threads = getenv("HERMES_NUM_THREADS”)
but I have no such environment variable set in my system... still, the code is parallelized!

2) In alternative, for debugging purpose: how do I set a line of code (e.g. a std::cout) so that it is executed on one thread at a time? I mean, the equivalent of "#pragma omp critical" in openMP

Thanks!
Daniele

**Comment by carmeloevoli** [comment]
1. if HERMES_NUM_THREADS is not set than the code uses the max number of threads allowed, see the line after https://github.com/cosmicrays/hermes/blob/cf6345893695e2cea5e128134da7fd44a04f1374/src/Common.cpp#L125
you can use `export HERMES_NUM_THREADS=1` before cmake to run HERMES on a single thread.

**Comment by adundovi** [comment]
Yes, as @carmeloevoli wrote, `export HERMES_NUM_THREADS=1` will run HERMES on a single thread.
