### ISSUE TITLE
HERMES Installation (request for help)

### ISSUE THREAD

**Issue by TejasSatheesh** [cosmicrays/hermes#23]
Hi,

I am facing an error while installing HERMES. While running the make -j command (in Linux operating system), I am getting some errors like ‘RingModel’ is not a member of ‘hermes::neutralgas’, ‘ring’ is not captured, base operand of ‘->’ is not a pointer, ‘gasType’ is not captured, 
and finally, 
make[2]: *** [CMakeFiles/hermes.dir/build.make:362: CMakeFiles/hermes.dir/src/integrators/PiZeroAbsorptionIntegrator.cpp.o] Error 1
make[2]: *** [CMakeFiles/hermes.dir/build.make:375: CMakeFiles/hermes.dir/src/integrators/PiZeroIntegrator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:619: CMakeFiles/hermes.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 47%] Linking CXX static library ../../libgtest.a
[ 47%] Built target gtest
make: *** [Makefile:141: all] Error 2

Any help in solving the errors would be really helpful. 

Thanks!
Tejas Satheesh

**Comment by adundovi** [comment]
Hi, please check if you have the CFITSIO library installed - the ring model does not work without it since it cannot open cosmic ray density FITS files. Thus, the ring model is automatically disabled when CFITSIO is not found. Which Linux distribution do you use?

**Comment by TejasSatheesh** [comment]
> Hi, please check if you have the CFITSIO library installed - the ring model does not work without it since it cannot open cosmic ray density FITS files. Thus, the ring model is automatically disabled when CFITSIO is not found. Which Linux distribution do you use?

Okay, so I downloaded the CFITSIO and ran the ./configure and the make commands for the CFITSIO installation and the CFITSIO installation was successful. (cfitsio-4.1.0 version) But, I am a bit confused on where do I place the installed CFITSIO folder? Because even after the installation I am getting CFITSIO not found when I run the HERMES installation. I use the Linux Mint 20 "Ulyana" cinnamon edition.

**Comment by TejasSatheesh** [comment]
> You should avoid installing software on Linux directly from source as long as you have other means. In this case, you should install `libcfitsio-dev` from a deb repository via apt. Mint is Ubuntu-compatible, thus, the Ubuntu (official) [repository](https://launchpad.net/ubuntu/+source/cfitsio) with libcfitsio-dev will suffice. Cmake will find packages installed like this for sure. On the other hand, installing them from source may require pointing cmake directly to the directory with required header files and binaries.

Okay, thanks for letting me know and also thanks a lot for helping me!! I was able to complete the installation with out any errors now.

**Comment by adundovi** [comment]
OK, great! Now, we can close the issue, right?

**Comment by TejasSatheesh** [comment]
> OK, great! Now, we can close the issue, right?

Yes we can close the issue. Thanks.
