### ISSUE TITLE
Dark matter annihilation with HERMES (request for help)

### ISSUE THREAD

**Issue by TejasSatheesh** [cosmicrays/hermes#24]
Hi,

Two questions regarding dark matter(DM) annihilation to gamma-rays using HERMES. 

1) The dark matter integrator takes two inputs, the spectrum and the profile. So, in the spectrum part, how do I extract the canonical cross section (<sigma.v> value) for a given DM annihilation channel?  

2) How do I include (or is it possible to include) the gamma-ray absorption in the ISRF medium for the DM annihilation case? 

Any help with the above questions would be really helpful. 

Thanks!
Tejas Satheesh

**Comment by carmeloevoli** [comment]
Hi Tejas,

1. The cross-section is fixed to the value 3 x 10^-26 cm3/s, see here: https://github.com/cosmicrays/hermes/blob/414f9bf96295b2742a8d266b15d6b0816648a77e/src/integrators/DarkMatterIntegrator.cpp#L36
As the flux is simply proportional to the cross-section value you can change by simply rescaling the result afterwards.

2. At this moment it is not possibile to have the absorption with the DM integrator. Thanks to let us know that you are interested, we will add in a next release. However, you could try to look at the implementation in the `PiZeroWithAbsorption` integrator and paste into the DM class. That would require some basic knowledge of C++ although.

**Comment by TejasSatheesh** [comment]
> Hi Tejas,
> 
> 1. The cross-section is fixed to the value 3 x 10^-26 cm3/s, see here: https://github.com/cosmicrays/hermes/blob/414f9bf96295b2742a8d266b15d6b0816648a77e/src/integrators/DarkMatterIntegrator.cpp#L36

Okay, thanks!

>    As the flux is simply proportional to the cross-section value you can change by simply rescaling the result afterwards.
> 2. At this moment it is not possibile to have the absorption with the DM integrator. Thanks to let us know that you are interested, we will add in a next release. However, you could try to look at the implementation in the `PiZeroWithAbsorption` integrator and paste into the DM class. That would require some basic knowledge of C++ although.

Okay. The project I am currently working on deals with gamma-ray absorption in DM annihilation gamma-ray flux. It will be really helpful if you can add it in the next release. And, I will try doing as per you suggested to look into the implementation in PiZeroWithAbsorption integrator and paste into DM class.   

Thanks a lot!
