### ISSUE TITLE
neutrino and antineutrino flux

### ISSUE THREAD

**Issue by danielegaggero** [cosmicrays/hermes#28]
Hi,

Important double check: The cross section returned in interactions/KelnerAharonianNeutrino ( F_numu + 2. * F_e ) refers to only neutrinos, right?
I assume that, in order to compute the total nu + nu_bar flux, we have to multiply the flux computed by HERMES by 2, as in eq. 52 and 53 of Kelner and Aharonian 2006. Could you confirm this?

Thanks a lot!!

**Comment by carmeloevoli** [comment]
ciao @danielegaggero, yes, this was also my take for the HERMES paper. Thanks for checking!
