### ISSUE TITLE
CMZ region in CO not read

### ISSUE THREAD

**Issue by carmeloevoli** [cosmicrays/hermes#3]
https://github.com/cosmicrays/hermes/blob/1587c84bf0f4620852f9c3bc5b3165360202c003/src/neutralgas/RingModel.cpp#L73

**Comment by carmeloevoli** [comment]
To include the CMZ in the calculations I first implemented two different boundary vectors for the HI and the CO case:
https://github.com/cosmicrays/hermes/blob/5db79b63919d97674f5365a478d800bf9b9cb8ad/include/hermes/neutralgas/RingModel.h#L48

then the correct order when using the rings is specified in 
https://github.com/cosmicrays/hermes/blob/5db79b63919d97674f5365a478d800bf9b9cb8ad/src/neutralgas/RingData.cpp#L62

**Comment by QRemy** [comment]
Thanks @carmeloevoli for the fix.

The far-CMZ component is truncated so better boundaries would be {0_kpc, 0.2_kpc, 0.86_kpc,...
However the cut of the CMZ and the far-CMZ from the rings was not done in R but in (l,v) space so there is some overlap between the two maps in longitude near l=1.3. For these components it would be even better to compute Rmin, Rmax separately. I would do something like that :
CMZ :
 Rmax = Rsun tan(lmax) with lmax = max(abs(l  where Wco_CMZ>0)) 
far-CMZ :
Rmax = Rsun tan(lmax) with lmax = max(l  where Wco_farCMZ>0) 
Rmin = Rsun tan(lmin) with lmin = min(l  where Wco_farCMZ>0) 

Alternatively to avoid losing informations at the overlap you could drop the CMZ/far-CMZ separation by summing the maps and use as boundaries {0_kpc, 0.86_kpc,...

**Comment by carmeloevoli** [comment]
Thanks @QRemy for the clarification.

I will implement the simpler alternative you suggested on Monday. I'm confident it will not significantly impact on large scale calculations.  Implementing the cut in (l,v) space is not so trivial in the `RingModel` class as it is now, but I plan to design a specific integrator for the CMZ region to be used when high-resolution maps in this window will be needed.

**Comment by QRemy** [comment]
It also seems that rings 10 and 11 are still completely empty while there should be (weak) emission from the two last rings.

**Comment by carmeloevoli** [comment]
yes, I confirm the problem. Working on it.

**Comment by carmeloevoli** [comment]
I fixed a bug that was present when we read the ring boundaries at:
https://github.com/cosmicrays/hermes/blob/0446fbe47a3f94fa8c6162ad91e39c50c5dea58a/src/neutralgas/RingModel.cpp#L59

After that change, the 11 rings of HI (the last is named `hvc' and I neglected) are read and accounted for computation. 

The CO rings are computed as you suggested adding the last two rings in the 0-th ring from 0 to 0.86 kpc: 
https://github.com/cosmicrays/hermes/blob/0446fbe47a3f94fa8c6162ad91e39c50c5dea58a/src/neutralgas/RingData.cpp#L66

Still the last CO ring is empty, but that should be because the pixels where the CO column density for that ring is larger than 0 are always directions along which the cosmic-ray density is negligible.

You can have a quick look to the gamma-ray flux computed for each CO and HI ring (still NSIDE=128) by getting this file [here](https://www.dropbox.com/s/c3hfe5aq9riaaaw/gammarings.zip?dl=0).

**Comment by carmeloevoli** [comment]
Indeed, I repeated the calculations with higher resolutions (in particular NSIDE=256 for the skymap) and now also the last CO ring has been populated. See the plots (~31 Mb) [here](https://www.dropbox.com/s/uvsy8q2yig5xkgl/GammaRings256.zip?dl=0).

**Comment by QRemy** [comment]
Thanks, that looks good, no further comments.
