### ISSUE TITLE
problem with Grid2D

### ISSUE THREAD

**Issue by carmeloevoli** [cosmicrays/hermes#33]
Grid2D is still based on Vector3D, which is clearly inconsistent.
Still it is used only for reading Dragon maps, so it is not an issue now but it might be for future users.

**Comment by adundovi** [comment]
Why this should be an issue? We just ignore one dimension in 3D to get 2D?

**Comment by carmeloevoli** [comment]
Does it work correctly also for rotation and all the operations?

**Comment by adundovi** [comment]
I don't know by heart, but if it doesn't we should fix it there. I would avoid re-implementing new vector class for 2D since the most vector properties are the same with 3D.

**Comment by carmeloevoli** [comment]
agree.
