### ISSUE TITLE
missing reference

### ISSUE THREAD

**Issue by carmeloevoli** [cosmicrays/hermes#38]
https://github.com/cosmicrays/hermes/blob/7d596dda5d1b4869bc13b594cc350181aca65b2e/src/interactions/DifferentialCrossSection.cpp#L28

where did we get these numbers? Also in the main paper we don't give any reference about this 😞

**Comment by adundovi** [comment]
Could this be from GammaSky?

**Comment by carmeloevoli** [comment]
I just checked, in GammaSky we adopted the A^2/3 scaling.

I remember we took from a paper, but I can't figure out which one.

**Comment by carmeloevoli** [comment]
I think is this but I have to check

https://ui.adsabs.harvard.edu/abs/2014PhRvD..90l3014K/abstract

**Comment by carmeloevoli** [comment]
Found it! It is this guy here:

https://ui.adsabs.harvard.edu/abs/2009APh....31..341M/abstract

I'm adding a comment to the code 🚀
