### ISSUE TITLE
latest update and python

### ISSUE THREAD

**Issue by danielegaggero** [cosmicrays/hermes#39]
Hi,

I installed the latest version, I get no error with cmake and the library is correctly installed. However, only the C++ library is there, in previous versions I also had pyhermes.cpython-37m-darwin.so (which could be loaded by any python script)

I have python3 correctly installed and linked via homebrew, and launched the usual
 cmake .. \
  -DPYTHON_EXECUTABLE=$PYTHON_BREW_PATH/bin/python3 \
  -DPYTHON_LIBRARY=$PYTHON_BREW_PATH/Frameworks/Python.framework/Versions/Current/lib/libpython3.10.dylib \
  -DPYTHON_INCLUDE_PATH=$PYTHON_BREW_PATH/Frameworks/Python.framework/Versions/Current/include \
  -DENABLE_TESTING=On

**Comment by danielegaggero** [comment]
I noticed that in CMakeLists.txt the flag
option(ENABLE_PYTHON "Create python library via Pybind11" ON)
was off. It's now set to ON, but still I don't see the pyhermes library as before...

**Comment by carmeloevoli** [comment]
This must be enabled in making as usual:
```sh
cmake -DENABLE_PYTHON=On ...
```

**Comment by danielegaggero** [comment]
It works now! On my system, -DENABLE_PYTHON=On does not work. However, cleaning CMakeCache.txt and setting option(ENABLE_PYTHON "Create python library via Pybind11" ON) in CMakeLists.txt did the job.
I would recommend to keep the flag ON as before, or warn the user in the INSTALL instructions that it has to be switched to ON
Thanks!
Daniele
