### ISSUE TITLE
Adding Integrators and Gas Types

### ISSUE THREAD

**Issue by fayezACE** [cosmicrays/hermes#40]
Hello:

I would like to generate a Skymap that include Inverse Compton, Pion Decay and Bremsstrahlung, and for the latter two, I want to include both HI and H2. I want a Skymap with all the relevant background light. How can I do that?

Thanks

**Comment by carmeloevoli** [comment]
HI @fayezACE, you have to generate the maps separately and then adding them up. 
Eventually you can write a new integrator to compute all of them but I don't see any advantage in doing so.

**Comment by fayezACE** [comment]
Do you mean to save the skymaps as for example numpy arrays, then sum them up?

**Comment by fayezACE** [comment]
Also, is there a built-in functionality to integrate over E_gamma?

**Comment by carmeloevoli** [comment]
> Do you mean to save the skymaps as for example numpy arrays, then sum them up?

yes

> Also, is there a built-in functionality to integrate over E_gamma?

no

**Comment by fayezACE** [comment]
Thank you!
