### ISSUE TITLE
A typo in your paper?

### ISSUE THREAD

**Issue by fayezACE** [cosmicrays/hermes#41]
Hello:

I am currently running some of you code and reading the paper. However, there is an issue that is confusing me. According to Figure 8. in your paper, pion decay through the contribution from HI dominates over that from H2, however, when you look at Figure 6 and compare the left image to the right, we can see that it is H2 that dominates over HI, at least near the galactic center (you can check the color bar). This is what I did when I ran your sample codes given in the file: e2-pizero-dragon2d.ipynb.
Is this a typo?

**Comment by carmeloevoli** [comment]
hi @fayezACE, the H2 and HI distributions are very different. Clumped the first, smoother the second. Thereby, one contribution dominated over the other depending on the region on which you are integrating the contribution. 

When you look towards the GC the H2 contribution is larger, but not if you integrate over the whole sky.

**Comment by fayezACE** [comment]
I understand, but Fig. 8 seems to suggest that H2 always dominates (Full Sky, Intermediate Latitudes, Inner Galaxy, Outer Galaxy). Looking inside the numpy arrays that make the plots H2 only dominates very close to the galactic center and is zero almost everywhere else. I am a bit confused on this point.

**Comment by fayezACE** [comment]
Exactly, It seems that HI dominates over H2, but if you look at figure 6, then you can see that it is H2 that dominates over HI, which is what I get when running the example code you provide. H2 (at least close to the galactic center), is larger than HI (for pion decay). This is the source of my confusion

**Comment by carmeloevoli** [comment]
You wrote: "Fig. 8 seems to suggest that H2 always dominates", Fig. 8 does not. Do we agree until here?

**Comment by fayezACE** [comment]
I am sorry, I meant HI always dominates. We agree. But from Fig 6, it seems that H2 dominates
