### ISSUE TITLE
A question on the code and plot 6

### ISSUE THREAD

**Issue by fayezACE** [cosmicrays/hermes#42]
Hello:

I have a question regarding  your plot 6 and the sample code. It is my understanding that the integrators yield the intensity, which for plot 6 is given by GeV cm^-2 sr^-1 s^-1. However, in the sample code you provide (e2-pizero-dragon2d.ipynb), the skymap gives a plot with units of TeV^-1 cm^-2 sr^-1 s^-1. What does this represent? and how do I get an intensity plot similar to plot 6 in your paper?

In addition, I would like to integrate over Egamma, how do I do that? From the C++ code, or is it possible to do it on the python code?

Thanks

**Comment by carmeloevoli** [comment]
> I have a question regarding your plot 6 and the sample code. It is my understanding that the integrators yield the intensity, which for plot 6 is given by GeV cm^-2 sr^-1 s^-1. However, in the sample code you provide (e2-pizero-dragon2d.ipynb), the skymap gives a plot with units of TeV^-1 cm^-2 sr^-1 s^-1. What does this represent? and how do I get an intensity plot similar to plot 6 in your paper?

The plot shows E^2 times the Intensity (which has units E^-1)


> In addition, I would like to integrate over Egamma, how do I do that? From the C++ code, or is it possible to do it on the python code?

You can do either in C++ or in Python.

**Comment by fayezACE** [comment]
Do you mean to say that in order to obtain plot 6, then I need to multiply the output of the integrator by Egamma^2?

**Comment by carmeloevoli** [comment]
Yep (provided you use units consistently).

**Comment by fayezACE** [comment]
But why does intensity have units of E^-1? It should be E s^-1 m^-2?

**Comment by carmeloevoli** [comment]
> But why does intensity have units of E^-1? It should be E s^-1 m^-2? 

The HERMES output is differential intensity, thereby per unit energy.

> Also, what I meant by the integration, is do I need to add it in one of the .h files where the other integrators are? Or is it possible to do in the Jupyter notebook itself?

Both should work.

**Comment by fayezACE** [comment]
Great! That clarifies it. I will try to work out how to integrate over the energy. Thank you
