### ISSUE TITLE
pyhermes module not created 

### ISSUE THREAD

**Issue by JordanKoechler** [cosmicrays/hermes#45]
Hi,
I am trying to install Hermes on MacOS in a conda environment. After linking the python interpreter in the env at the cmake step, the installation and the tests went well, meaning that the C++ part works correctly. But even if I turn on the -DENABLE_PYTHON flag, PyBind doesn't seem to create the python library.

Do you have an idea on how to solve this issue?

Thanks!
Jordan Koechler

**Comment by adundovi** [comment]
Hi Jordan,

I'm sorry for not following the HERMES issues for a long time. The cmake part which finds Python is now re-done, so you can try again with:

```sh
    cmake \
         -DPython3_EXECUTABLE=${PYTHON_BREW_PATH}/bin/python3 \
         -DPython3_INCLUDE_DIRS=${PYTHON_BREW_PATH}/ ... \
         -DPython3_LIBRARIES=${PYTHON_BREW_PATH}/lib/ ... \
         -DENABLE_PYTHON=On \
```

However, I would recommend using a Docker imager which includes Jupyter and HERMES:

  ```sh
  docker run -it --rm -p 8888:8888 quay.io/cosmicrays/jupyter-hermes:latest
  ```
