### ISSUE TITLE
Help for resources

### ISSUE THREAD

**Issue by SriGoli-0123** [cosmicrays/hermes#46]
Hello, 

Can I get the links and papers which were used for writing the exact equations and code in RingModel.cpp, Nakanishi06.cpp and RingData.cpp? I could not find any, even in DRAGON2 paper.

Thank you,
Harshith

**Comment by carmeloevoli** [comment]
Please check here: https://ui.adsabs.harvard.edu/abs/2021A%26A...653A..18D/abstract
