### ISSUE TITLE
Unable to locate libfftw3-3 and libcfitsio9

### ISSUE THREAD

**Issue by SriGoli-0123** [cosmicrays/hermes#47]
Hi,
While building the docker image using the command 
**sudo docker build -t jupyter-pyhermes .**
it shows the below error

> (hermes) harshith@user-System-Product-Name:~/hermes$ sudo docker build -t jupyter-pyhermes . 
[+] Building 21.5s (9/18)                                                                                                                                                                    docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s
 => => transferring dockerfile: 2.35kB                                                                                                                                                                 0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 7)                                                                                                                         0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 57)                                                                                                                        0.0s
 => [internal] load metadata for quay.io/jupyter/scipy-notebook:latest                                                                                                                                11.3s
 => [internal] load metadata for quay.io/jupyter/docker-stacks-foundation:latest                                                                                                                      16.5s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => CACHED [builder 1/7] FROM quay.io/jupyter/docker-stacks-foundation:latest@sha256:734ec49e3b1b2c82e0ec8561c13accc1da2ef2189082c8ab76d496f9119dae2e                                                  0.0s
 => [internal] load build context                                                                                                                                                                      0.1s
 => => transferring context: 144.33kB                                                                                                                                                                  0.1s
 => CACHED [runner 1/6] FROM quay.io/jupyter/scipy-notebook:latest@sha256:1252ff3c9df718b76a828fe597efb56cceedc98871649234f856bad9d8937550                                                             0.0s
 => ERROR [runner 2/6] RUN apt-get update --yes &&     apt-get install --yes --no-install-recommends     libgsl27     libfftw3-3     libcfitsio9 &&     apt-get clean && rm -rf /var/lib/apt/lists/*   4.9s
 => CANCELED [builder 2/7] RUN apt-get update --yes &&     apt-get install --yes --no-install-recommends     build-essential     pkg-config     cmake     git     doxygen     graphviz     libgsl-dev  4.9s
                                                                                                                                                                                                  
 > [runner 2/6] RUN apt-get update --yes &&     apt-get install --yes --no-install-recommends     libgsl27     libfftw3-3     libcfitsio9 &&     apt-get clean && rm -rf /var/lib/apt/lists/*:              
0.539 Get:1 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]                                                                                                                             
0.543 Get:2 http://archive.ubuntu.com/ubuntu noble InRelease [256 kB]                                                                                                                                       
1.357 Get:3 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [586 kB]                                                                                                                   
1.405 Get:4 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]                                                                                                                               
1.616 Get:5 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]                                                                                                                             
2.004 Get:6 http://archive.ubuntu.com/ubuntu noble/restricted amd64 Packages [117 kB]                                                                                                                       
2.008 Get:7 http://security.ubuntu.com/ubuntu noble-security/multiverse amd64 Packages [15.3 kB]                                                                                                            
2.012 Get:8 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [725 kB]                                                                                                               
2.057 Get:9 http://archive.ubuntu.com/ubuntu noble/multiverse amd64 Packages [331 kB]                                                                                                                       
2.198 Get:10 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Packages [548 kB]                                                                                                            
2.208 Get:11 http://archive.ubuntu.com/ubuntu noble/main amd64 Packages [1808 kB]
2.529 Get:12 http://archive.ubuntu.com/ubuntu noble/universe amd64 Packages [19.3 MB]
3.604 Get:13 http://archive.ubuntu.com/ubuntu noble-updates/multiverse amd64 Packages [18.4 kB]
3.604 Get:14 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [812 kB]
3.621 Get:15 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [932 kB]
3.669 Get:16 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Packages [548 kB]
3.710 Get:17 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Packages [11.8 kB]
4.048 Fetched 26.4 MB in 4s (6800 kB/s)
4.048 Reading package lists...
4.408 Reading package lists...
4.767 Building dependency tree...
4.839 Reading state information...
**4.849 E: Unable to locate package libfftw3-3
4.849 E: Unable to locate package libcfitsio9**
------
> Dockerfile:61
--------------------
 > 60 |     
  61 | >>> RUN apt-get update --yes && \ 
  62 | >>>     apt-get install --yes --no-install-recommends \
  63 | >>>     libgsl27 \
  64 | >>>     libfftw3-3 \
  65 | >>>     libcfitsio9 && \
  66 | >>>     apt-get clean && rm -rf /var/lib/apt/lists/*
  67 |     
--------------------
>ERROR: failed to solve: process "/bin/bash -o pipefail -c apt-get update --yes &&     apt-get install --yes --no-install-recommends     libgsl27     libfftw3-3     libcfitsio9 &&     apt-get clean && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

the libraries libcfitsio9 and libfftw3-3 are not to be found when building the docker image, but they are installed when 
**sudo apt install libcfitsio9 libfftw3-3**
is used.

can someone help me with resolving this error and completing the Hermes installation, so I can run it locally with my modifications?
Thanks!

**Comment by adundovi** [comment]
Hi @SriGoli-0123, I'll check the docker build procedure again and report back here.

**Comment by adundovi** [comment]
The [underlying/base docker image](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html) has changed, or to be more precise its Ubuntu version, so some packages changed their names, including `fftw` and `cfitsio` which are now: `libfftw3-single3`, `libfftw3-double3`, and `libcfitsio10t64`. Thus, I've updated the Dockerfile and it is working now. You can check it by pulling the newest master/main branch.

**Comment by adundovi** [comment]
Closed with  07f26bdb7d68eda1c1f84ee3cc806c588c1f6f3a.

**Comment by SriGoli-0123** [comment]
Thank you...

Also, if I want to modify the equations of a particular model, for example in Nakanishi06.cpp, or create a new file and run it, where should the necessary changes be made in the entire master/main branch? 

Because the Dockerfile was showing errors while building the docker image, after modifying some equations in Nakanishi06.cpp code.

Can you also provide the papers and resources used to write the exact equations and numbers used in the Nakanishi06.cpp and RingModel.cpp codes?... since neither were they mentioned in the DRAGON2 paper, or the HERMES paper or any reference...

For example, the exact numbers and equations of these functions below

>QPDensity Nakanishi06::getHIDensity(const Vector3QLength &pos) const {
	const QLength h_0 = 1.06_pc;
	const QPDensity n_0 = 0.94 / 1_cm3;
	double r_kpc = static_cast<double>(pos.getR() / 1_kpc);
	double exp_1 = std::exp(-r_kpc / 2.4);
	double exp_2 = std::exp(-std::pow((r_kpc - 9.5) / 4.8, 2));
	QLength scaleHeight =
	    h_0 * (116.3 + 19.3 * r_kpc + 4.1 * std::pow(r_kpc, 2) -
	           0.05 * std::pow(r_kpc, 3));
	QPDensity densityOnPlane = n_0 * (0.6 * exp_1 + 0.24 * exp_2);
	return densityOnPlane * exp(-M_LN2 * pow<2>(pos.z / scaleHeight));
}

>QPDensity Nakanishi06::getH2Density(const Vector3QLength &pos) const {
	double z_kpc = static_cast<double>(pos.z / 1_kpc);
	double r_kpc = static_cast<double>(pos.getR() / 1_kpc);
	double E1 = 11.2 * std::exp(-pow<2>(r_kpc) / 0.874);
	double E2 = 0.83 * std::exp(-pow<2>((r_kpc - 4.0) / 3.2));
	double h = 1.06e-3 * (10.8 * std::exp(0.28 * r_kpc) + 42.78);
	return 2.0 * 0.94 * (E1 + E2) * std::exp(-M_LN2 * pow<2>(z_kpc / h)) /
	       1_cm3;
}

Please help me with this...
Thanks

**Comment by adundovi** [comment]
Hi @SriGoli-0123,

I would suggest that you make a copy of the header and source files of `Nakanishi06` and you make your modifications there.

Regarding the source of equations - it is cited in the source code:

https://github.com/cosmicrays/hermes/blob/07f26bdb7d68eda1c1f84ee3cc806c588c1f6f3a/src/neutralgas/Nakanishi06.cpp#L8

Hope this helps.
