### ISSUE TITLE
Experimenting with codes in HERMES

### ISSUE THREAD

**Issue by SriGoli-0123** [cosmicrays/hermes#48]
Hi,

I want to modify the equations of a particular model, for example in Nakanishi06.cpp, or create a new cpp or python file and run it without errors.

Can you provide the papers and resources used to write the exact equations and numbers used in the Nakanishi06.cpp and RingModel.cpp codes?... since neither were they mentioned in the DRAGON2 paper, or the HERMES paper or any reference...

For example, the exact numbers and equations of these functions given below snippet from Nakanishi06.cpp...

I also want to generate multiple values of densities by varying parameters and equations, that too in such a way that when I call an integrator function like the PiZeroIntegrator, it should take multiple values of 
**neutralgas.RingModel()** of a particular gas chosen, to generate different plots and skymaps possible.

>QPDensity Nakanishi06::getHIDensity(const Vector3QLength &pos) const {
const QLength h_0 = 1.06_pc;
const QPDensity n_0 = 0.94 / 1_cm3;
double r_kpc = static_cast(pos.getR() / 1_kpc);
double exp_1 = std::exp(-r_kpc / 2.4);
double exp_2 = std::exp(-std::pow((r_kpc - 9.5) / 4.8, 2));
QLength scaleHeight =
h_0 * (116.3 + 19.3 * r_kpc + 4.1 * std::pow(r_kpc, 2) -
0.05 * std::pow(r_kpc, 3));
QPDensity densityOnPlane = n_0 * (0.6 * exp_1 + 0.24 * exp_2);
return densityOnPlane * exp(-M_LN2 * pow<2>(pos.z / scaleHeight));
}

>QPDensity Nakanishi06::getH2Density(const Vector3QLength &pos) const {
double z_kpc = static_cast(pos.z / 1_kpc);
double r_kpc = static_cast(pos.getR() / 1_kpc);
double E1 = 11.2 * std::exp(-pow<2>(r_kpc) / 0.874);
double E2 = 0.83 * std::exp(-pow<2>((r_kpc - 4.0) / 3.2));
double h = 1.06e-3 * (10.8 * std::exp(0.28 * r_kpc) + 42.78);
return 2.0 * 0.94 * (E1 + E2) * std::exp(-M_LN2 * pow<2>(z_kpc / h)) /
1_cm3;
}

Please help me with my doubts...
Thanks

**Comment by carmeloevoli** [comment]
You might find useful to look to the original Nakanishi and Sofue 2006 paper:

- https://ui.adsabs.harvard.edu/abs/2006PASJ...58..847N/abstract
- https://ui.adsabs.harvard.edu/abs/2003PASJ...55..191N/abstract
