### ISSUE TITLE
Problem with Masks

### ISSUE THREAD

**Issue by danielegaggero** [cosmicrays/hermes#8]
The rectangular mask seems to have a problem.

For instance if I set
mask_edges = ([5*deg, 0*deg], [-5*deg, 180*deg])
mask = RectangularWindow(*mask_edges)

I think I actually get the [0,5*deg] in latitude

**Comment by adundovi** [comment]
Hi Daniele,
maybe I changed the definition and it is not changed in the documentation.

```c++
    RectangularWindow(const std::array<QAngle, 2> &latitude,
                      const std::array<QAngle, 2> &longitude);
```
It is, first, latitude in galactic coordinates, and then longitude in galactic coordinates. Please check if it works.

**Comment by danielegaggero** [comment]
ok great, it works now! thanks
